apiVersion: apps/v1
kind: Deployment
metadata:
    name: location
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
      - name: location-api
        image: nerodro/location
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: ImagePrefix
          value: http://localhost
  selector:
    matchLabels:
      app: location
---
apiVersion: v1
kind: Service
metadata:
  name: location
spec:
  type: NodePort
  ports:
  - name: "http"
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: location
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-api
        image: nerodro/user
        ports:
        - containerPort: 9002
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: user
