// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VacancieRepository;

#nullable disable

namespace VacancieRepository.Migrations
{
    [DbContext(typeof(VacancyContext))]
    [Migration("20231130161741_List")]
    partial class List
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VacancieDomain.Model.ResponseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CvId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VacancieId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VacancieId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("VacancieDomain.Model.VacancieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutWork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vacanies");
                });

            modelBuilder.Entity("VacancieDomain.Model.ResponseModel", b =>
                {
                    b.HasOne("VacancieDomain.Model.VacancieModel", "Vacancie")
                        .WithMany("ResponseModel")
                        .HasForeignKey("VacancieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacancie");
                });

            modelBuilder.Entity("VacancieDomain.Model.VacancieModel", b =>
                {
                    b.Navigation("ResponseModel");
                });
#pragma warning restore 612, 618
        }
    }
}
